# Generated by Django 4.0.3 on 2022-07-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
