# Generated by Django 4.0.3 on 2022-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_text_test_text_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='text',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='photo',
        ),
        migrations.AddField(
            model_name='productos',
            name='photo',
            field=models.ManyToManyField(to='base.photos'),
        ),
    ]
