# Generated by Django 4.0.3 on 2022-07-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_productos_text_remove_productos_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='photo',
            new_name='photos',
        ),
    ]
